// app/guide/itr-blogs/form-16/page.tsx

import Link from "next/link";
import Script from "next/script";
import Footar from "@/components/Footar";
import type { Metadata } from "next";
import {
  ArrowRight,
  BadgeCheck,
  BookOpen,
  Calculator,
  CheckCircle,
  ChevronRight,
  Clock,
  FileText,
  IndianRupee,
  Info,
  MessageCircle,
  Shield,
  Star,
  AlertCircle,
  Download,
  Search,
  Users,
  Building2,
} from "lucide-react";

/* ─── Metadata ──────────────────────────────────────────────────────────── */

export const metadata: Metadata = {
  title: "Form 16: What Is It, Parts A & B, How to Get It | Taxvio Guide",
  description:
    "Form 16 is the TDS certificate issued by your employer for salary income. Learn what Form 16 contains, the difference between Part A and Part B, how to download it, how to use it for ITR filing, and what to do if your employer has not issued it.",
  keywords: [
    "Form 16",
    "what is Form 16",
    "Form 16 Part A and Part B",
    "Form 16 TDS certificate",
    "Form 16 for ITR filing",
    "how to get Form 16",
    "Form 16 download TRACES",
    "Form 16 salary TDS",
    "Form 16 from employer",
    "Form 16 income tax",
    "Form 16A vs Form 16",
    "Form 16 for salaried employees",
  ],
  alternates: {
    canonical: "https://www.taxvio.in/guide/itr-blogs/form-16",
  },
  openGraph: {
    title: "Form 16: What Is It, Part A & B, How to Get It | Taxvio",
    description:
      "A complete guide to Form 16 — the TDS certificate your employer issues for salary income. Learn what it contains, how to use it for ITR filing, and what to do if it is missing.",
    url: "https://www.taxvio.in/guide/itr-blogs/form-16",
    siteName: "Taxvio",
    type: "article",
  },
  twitter: {
    card: "summary_large_image",
    title: "Form 16 Complete Guide: Part A, Part B & ITR Filing",
    description:
      "Everything salaried employees need to know about Form 16 — TDS certificate, Part A vs Part B, download from TRACES, and ITR filing.",
  },
  robots: { index: true, follow: true },
};

/* ─── Data ───────────────────────────────────────────────────────────────── */

const PART_A_DETAILS = [
  { item: "Employer Name & TAN", desc: "Legal name and Tax Deduction Account Number of the employer who deducted TDS from your salary." },
  { item: "Employee Name & PAN", desc: "Your full name and Permanent Account Number as registered with the employer for TDS purposes." },
  { item: "Period of Employment", desc: "The financial year period during which you were employed with this specific employer and TDS was deducted." },
  { item: "Summary of TDS Deposited", desc: "Quarter-wise breakup of salary paid and TDS deposited to the government — verified against TRACES records." },
  { item: "Challan Details", desc: "BSR code, challan serial number and date of TDS deposit for each quarter — matching the employer's TDS return." },
  { item: "TRACES Certificate Number", desc: "A unique certificate number generated by TRACES confirming the authenticity of Part A." },
];

const PART_B_DETAILS = [
  { item: "Gross Salary Breakup", desc: "Basic salary, House Rent Allowance (HRA), Leave Travel Allowance, special allowances, bonus and other salary components." },
  { item: "Exempt Allowances", desc: "HRA exemption computed under Section 10(13A), LTA exemption under Section 10(5), and other eligible exempt allowances under Section 10." },
  { item: "Standard Deduction", desc: "₹50,000 (old regime) or ₹75,000 (new regime) standard deduction applicable to salaried employees and pensioners." },
  { item: "Professional Tax", desc: "Professional tax deducted by the employer from salary and eligible as a deduction under Section 16(iii)." },
  { item: "Income from Other Sources (Reported)", desc: "Interest from savings accounts or other income declared by the employee to the employer for consolidated TDS computation." },
  { item: "Chapter VI-A Deductions", desc: "Section 80C investments (PF, PPF, ELSS, LIC), Section 80D health insurance premiums, Section 80E education loan interest, and other eligible deductions." },
  { item: "Net Taxable Income", desc: "Gross salary minus exemptions and deductions — the income on which the employer computes the final tax liability." },
  { item: "Tax Payable & TDS Deducted", desc: "Total income tax payable on net taxable income and the actual TDS deducted and deposited during the year." },
];

const FAQS = [
  {
    question: "What is Form 16?",
    answer:
      "Form 16 is a TDS (Tax Deducted at Source) certificate issued by an employer to a salaried employee under Section 203 of the Income Tax Act, 1961. It certifies that the employer has deducted income tax from the employee's salary and deposited the same with the Central Government. Form 16 is the primary document used by salaried employees to file their Income Tax Return (ITR). It consists of two parts — Part A downloaded from TRACES and Part B prepared by the employer.",
  },
  {
    question: "What is the difference between Form 16, Form 16A and Form 16B?",
    answer:
      "Form 16 is a TDS certificate specifically for salary income — issued by employers to employees. Form 16A is a TDS certificate for non-salary income such as bank interest, professional fees, rent received, commission or contractor payments deducted under various sections other than Section 192. Form 16B is a TDS certificate issued by the buyer of immovable property to the seller for TDS deducted under Section 194IA on property purchase transactions above ₹50 lakh.",
  },
  {
    question: "Is it mandatory for an employer to issue Form 16?",
    answer:
      "Yes. Under Section 203 of the Income Tax Act, every employer who deducts TDS from an employee's salary is legally required to issue Form 16 to the employee by June 15 of the assessment year — that is, by June 15, 2025 for FY 2024-25. If the employer fails to issue Form 16 within this deadline, a penalty of ₹100 per day may apply under Section 272A(2)(g) until the certificate is issued.",
  },
  {
    question: "Can I file ITR without Form 16?",
    answer:
      "Yes, you can file your ITR without Form 16, though it requires more effort. You need your salary slips for all months in the financial year, Form 26AS and AIS to identify TDS credited against your PAN, bank statements for salary credits, and investment proofs for deductions. The income figures from your salary slips and the TDS credits from Form 26AS together give you the data needed to prepare and file the return. Taxvio can assist you with ITR filing even when Form 16 is unavailable.",
  },
  {
    question: "What should I do if Form 16 has wrong information?",
    answer:
      "If your Form 16 contains errors — wrong salary figures, missing deductions, incorrect PAN, or wrong HRA calculation — you should immediately contact your employer's HR or payroll department and request a revised Form 16. The employer must correct the TDS return filed with TRACES and issue a fresh Form 16 with the corrected data. Do not file your ITR based on an incorrect Form 16, as mismatches against Form 26AS will trigger a Section 143(1) demand.",
  },
  {
    question: "How is Form 16 different from payslips?",
    answer:
      "A payslip shows the salary computation and deductions for a single month. Form 16 is an annual document that consolidates your entire financial year's salary, exemptions, deductions, and tax computation — certified by the employer and verified against TRACES records. Form 16 is a legal tax certificate; payslips are internal payroll documents. For income tax purposes, Form 16 is the authoritative document.",
  },
  {
    question: "Can I get Form 16 from the income tax portal directly?",
    answer:
      "Not directly. Only Part A of Form 16 is generated by TRACES and is available to the employer for download. The employer then issues it to you. Part B is prepared by the employer independently. You cannot download your own Form 16 from the income tax portal as an employee. However, you can verify TDS credits on your Form 16 against what appears in your Form 26AS on the income tax portal.",
  },
];

/* ─── Schemas ───────────────────────────────────────────────────────────── */

const articleSchema = {
  "@context": "https://schema.org",
  "@type": "Article",
  headline: "Form 16: What Is It, Part A and Part B, How to Get It and Use It for ITR Filing",
  description:
    "Complete guide to Form 16 — the employer-issued salary TDS certificate. Learn about Part A and Part B, how to download, reconcile with Form 26AS, and file ITR.",
  url: "https://www.taxvio.in/guide/itr-blogs/form-16",
  mainEntityOfPage: {
    "@type": "WebPage",
    "@id": "https://www.taxvio.in/guide/itr-blogs/form-16",
  },
  author: { "@type": "Organization", name: "Taxvio", url: "https://www.taxvio.in" },
  publisher: { "@type": "Organization", name: "Taxvio", url: "https://www.taxvio.in" },
  dateModified: "2025-04-01",
  wordCount: 2200,
  inLanguage: "en-IN",
  articleSection: "Income Tax",
  keywords: ["Form 16", "TDS certificate", "salary TDS", "ITR filing", "Part A Part B"],
};

const breadcrumbSchema = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "Home", item: "https://www.taxvio.in" },
    { "@type": "ListItem", position: 2, name: "ITR Guides", item: "https://www.taxvio.in/guide/itr-blogs" },
    { "@type": "ListItem", position: 3, name: "Form 16", item: "https://www.taxvio.in/guide/itr-blogs/form-16" },
  ],
};

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: FAQS.map(({ question, answer }) => ({
    "@type": "Question",
    name: question,
    acceptedAnswer: { "@type": "Answer", text: answer },
  })),
};

/* ─── Reusable components ────────────────────────────────────────────────── */

function InfoBox({
  title,
  children,
  color = "blue",
}: {
  title: string;
  children: React.ReactNode;
  color?: "blue" | "green" | "amber" | "rose";
}) {
  const styles = {
    blue:  "border-blue-100  bg-blue-50  text-blue-900",
    green: "border-emerald-100 bg-emerald-50 text-emerald-900",
    amber: "border-amber-100 bg-amber-50 text-amber-900",
    rose:  "border-rose-100  bg-rose-50  text-rose-900",
  };
  return (
    <div className={`rounded-2xl border p-5 ${styles[color]}`}>
      <div className="mb-2 flex items-center gap-2">
        <Info size={15} className="shrink-0" />
        <h3 className="text-sm font-extrabold">{title}</h3>
      </div>
      <div className="text-sm leading-relaxed">{children}</div>
    </div>
  );
}

function SectionHeader({
  eyebrow,
  heading,
  icon: Icon,
}: {
  eyebrow: string;
  heading: string;
  icon: React.ElementType;
}) {
  return (
    <div className="mb-6 flex items-start gap-3">
      <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-[#00416a]/10">
        <Icon size={17} className="text-[#00416a]" />
      </div>
      <div>
        <p className="text-xs font-bold uppercase tracking-widest text-[#0077b6]">{eyebrow}</p>
        <h2 className="mt-1 text-xl font-extrabold text-[#00416a] md:text-2xl">{heading}</h2>
      </div>
    </div>
  );
}

/* ─── Page ───────────────────────────────────────────────────────────────── */

export default function Form16Page() {
  return (
    <>
      <Script id="form16-article-schema" type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }} />
      <Script id="form16-breadcrumb-schema" type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
      <Script id="form16-faq-schema" type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />

      <main className="bg-[#f8fbfd] font-sans text-gray-800">

        {/* ════════ HERO ════════ */}
        <section className="relative overflow-hidden bg-[#00416a] text-white">
          <div className="absolute inset-0 bg-gradient-to-br from-[#00416a] via-[#003257] to-[#001e36]" />
          <div className="absolute inset-0 opacity-[0.04] pointer-events-none"
            style={{ backgroundImage: "linear-gradient(#fff 1px,transparent 1px),linear-gradient(90deg,#fff 1px,transparent 1px)", backgroundSize: "50px 50px" }} />
          <div className="absolute top-0 right-0 w-[620px] h-[620px] rounded-full pointer-events-none"
            style={{ background: "radial-gradient(circle,rgba(56,189,248,0.14) 0%,transparent 65%)" }} />
          <div className="absolute bottom-0 left-0 w-[420px] h-[420px] rounded-full pointer-events-none"
            style={{ background: "radial-gradient(circle,rgba(45,212,191,0.09) 0%,transparent 65%)" }} />

          <div className="relative max-w-6xl mx-auto px-6 pt-20 pb-14 md:pt-28">
            {/* Breadcrumb */}
            <nav className="mb-8" aria-label="Breadcrumb">
              <ol className="flex flex-wrap items-center gap-2 text-xs text-white/50">
                <li><Link href="/" className="hover:text-white transition">Home</Link></li>
                <ChevronRight size={11} className="text-white/25" />
                <li><Link href="/guide/itr-blogs" className="hover:text-white transition">ITR Guides</Link></li>
                <ChevronRight size={11} className="text-white/25" />
                <li className="text-white/80 font-semibold">Form 16</li>
              </ol>
            </nav>

            <div className="grid md:grid-cols-[1fr_320px] gap-12 items-center">
              <div>
                <div className="inline-flex items-center gap-2 rounded-full px-4 py-1.5 text-xs font-bold mb-6 backdrop-blur-sm"
                  style={{ background: "rgba(255,255,255,0.10)", border: "1px solid rgba(255,255,255,0.18)" }}>
                  <span className="w-2 h-2 rounded-full bg-green-400 animate-pulse shrink-0" />
                  FY 2024-25 · Issued by June 15, 2025
                </div>

                <h1 className="text-4xl md:text-5xl font-extrabold leading-[1.08] tracking-tight text-white">
                  Form 16 —
                  <span className="block mt-2 bg-gradient-to-r from-sky-300 to-teal-300 bg-clip-text text-transparent">
                    Your Salary TDS Certificate
                  </span>
                </h1>

                <p className="mt-5 text-white/75 text-base md:text-lg leading-relaxed max-w-2xl">
                  <strong className="text-white">Form 16</strong> is the TDS
                  certificate your employer issues every year confirming how much
                  salary was paid and how much income tax was deducted and
                  deposited. It is the single most important document for a
                  salaried employee filing an ITR.
                </p>

                <div className="mt-8 flex flex-col sm:flex-row gap-3">
                  <Link href="/serviceslist/income-tax/itr-salaried"
                    className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-7 py-3.5 text-[#00416a] text-sm font-bold shadow-xl hover:bg-gray-50 active:scale-[0.97] transition-all">
                    File ITR with Form 16 <ArrowRight size={15} />
                  </Link>
                  <Link href="/contact"
                    className="inline-flex items-center justify-center gap-2 rounded-xl border-2 border-white/35 bg-white/5 px-7 py-3.5 text-white text-sm font-bold hover:bg-white/10 hover:border-white active:scale-[0.97] transition-all">
                    Ask a Tax Expert <MessageCircle size={15} />
                  </Link>
                </div>
              </div>

              {/* Quick card */}
              <div className="rounded-3xl p-6 shadow-2xl backdrop-blur-sm border border-white/15"
                style={{ background: "rgba(255,255,255,0.08)" }}>
                <p className="text-xs font-bold uppercase tracking-[0.18em] text-white/45 mb-5">
                  Form 16 at a glance
                </p>
                <div className="space-y-4">
                  {[
                    { icon: Building2,   title: "Issued by",        text: "Your employer (every company deducting TDS)" },
                    { icon: Clock,       title: "Deadline",          text: "June 15 of the assessment year" },
                    { icon: FileText,    title: "Two parts",         text: "Part A from TRACES · Part B from employer" },
                    { icon: IndianRupee, title: "Used for",          text: "ITR filing, loan applications, visa processing" },
                    { icon: Users,       title: "Who gets it",       text: "Salaried employees with TDS deducted from salary" },
                  ].map(({ icon: Icon, title, text }) => (
                    <div key={title} className="flex items-start gap-3 border-b border-white/10 pb-4 last:border-0 last:pb-0">
                      <div className="w-9 h-9 rounded-xl bg-sky-400/15 flex items-center justify-center shrink-0">
                        <Icon size={16} className="text-sky-300" />
                      </div>
                      <div>
                        <p className="text-xs font-extrabold text-white/50 uppercase tracking-wide">{title}</p>
                        <p className="text-sm font-bold text-white mt-0.5 leading-snug">{text}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>

          {/* Trust strip */}
          <div className="relative border-t border-white/10">
            <div className="max-w-6xl mx-auto px-6 py-4 flex flex-wrap items-center justify-center gap-x-8 gap-y-2">
              {[
                { icon: BadgeCheck, text: "CA-Assisted Tax Guidance" },
                { icon: Shield,     text: "Secure & Confidential" },
                { icon: Clock,      text: "Simple Explanations" },
                { icon: Star,       text: "4.9★ Taxvio Rating" },
              ].map(({ icon: Icon, text }) => (
                <div key={text} className="flex items-center gap-1.5 text-white/55 text-xs">
                  <Icon size={12} className="text-sky-400" /> {text}
                </div>
              ))}
            </div>
          </div>

          <svg viewBox="0 0 1440 48" fill="none" className="w-full block">
            <path d="M0 48L1440 48L1440 24C1200 48 900 0 720 16C540 32 240 48 0 24L0 48Z" fill="#f8fbfd" />
          </svg>
        </section>

        {/* ════════ ARTICLE + SIDEBAR ════════ */}
        <section className="py-16 md:py-20">
          <div className="max-w-6xl mx-auto px-6 grid lg:grid-cols-[minmax(0,1fr)_280px] gap-10">

            {/* ── Main Article ── */}
            <article className="min-w-0 bg-white rounded-3xl border border-gray-100 shadow-sm p-6 md:p-10">

              {/* Intro */}
              <div className="pb-10 border-b border-gray-100">
                <p className="text-xs font-bold uppercase tracking-[0.18em] text-[#0077b6] mb-4">
                  Income Tax Guide
                </p>
                <h2 className="text-2xl md:text-3xl font-extrabold text-[#00416a] leading-tight">
                  What Is Form 16 and Who Needs It?
                </h2>

                <p className="mt-5 text-sm leading-8 text-gray-600">
                  <strong>Form 16</strong> is a TDS (Tax Deducted at Source)
                  certificate issued by an employer to a salaried employee under
                  Section 203 of the Income Tax Act, 1961. It officially confirms
                  that the employer has deducted income tax from the employee's
                  salary during the financial year and deposited the same with
                  the Central Government on the employee's behalf.
                </p>

                <p className="mt-4 text-sm leading-8 text-gray-600">
                  Every salaried individual in India — whether a private sector
                  employee, a government employee, a contractual worker receiving
                  regular salary, or a director drawing remuneration from a
                  company — should receive Form 16 from their employer if TDS
                  has been deducted from their salary. Even if your income falls
                  below the taxable threshold and no TDS was deducted, it is a
                  good practice to request a nil-TDS acknowledgement or a letter
                  confirming salary paid, since Form 16 is also commonly required
                  for home loan applications, education loan processing, and
                  certain visa applications.
                </p>

                <p className="mt-4 text-sm leading-8 text-gray-600">
                  The last date by which employers must issue Form 16 to employees
                  is <strong>June 15</strong> following the end of the financial
                  year — for example, June 15, 2025 for FY 2024-25. Employers
                  who fail to issue Form 16 by this deadline risk a penalty of
                  ₹100 per day of default under Section 272A(2)(g) of the Income
                  Tax Act.
                </p>

                <InfoBox title="Form 16 is not the same as Form 16A or Form 16B" color="blue">
                  <p>
                    Form 16 is specifically for salary income. Form 16A is issued
                    by banks, clients and companies for non-salary TDS — such as
                    interest, professional fees and rental income. Form 16B is
                    issued by a property buyer to the seller for TDS under Section
                    194IA on property transactions. Always verify which form you
                    need before filing your ITR.
                  </p>
                </InfoBox>
              </div>

              {/* Part A */}
              <section id="part-a" className="pt-10 scroll-mt-24">
                <SectionHeader
                  eyebrow="Official TRACES document"
                  heading="Form 16 Part A — What It Contains"
                  icon={FileText}
                />

                <p className="text-sm leading-8 text-gray-600">
                  Part A of Form 16 is the officially government-generated
                  component. It is downloaded by your employer directly from the
                  TRACES (TDS Reconciliation Analysis and Correction Enabling
                  System) portal and carries a unique TRACES certificate number
                  that makes it tamper-evident. Part A primarily deals with the
                  tax side of the salary relationship — confirming how much was
                  deducted and deposited, quarter by quarter.
                </p>

                <div className="mt-6 grid sm:grid-cols-2 gap-4">
                  {PART_A_DETAILS.map(({ item, desc }) => (
                    <div key={item}
                      className="rounded-2xl border border-blue-100 bg-blue-50 p-4">
                      <div className="flex items-start gap-2">
                        <CheckCircle size={14} className="text-blue-600 mt-0.5 shrink-0" />
                        <div>
                          <p className="text-xs font-extrabold text-blue-900">{item}</p>
                          <p className="mt-1 text-xs leading-relaxed text-blue-800/70">{desc}</p>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>

                <InfoBox title="Verify authenticity using TRACES" color="green">
                  <p>
                    Any Form 16 Part A that does not carry a TRACES watermark
                    and unique certificate number should be treated as potentially
                    invalid. Employees can verify the authenticity of their
                    Form 16 Part A on the TRACES portal using the certificate
                    number printed on the document.
                  </p>
                </InfoBox>
              </section>

              {/* Part B */}
              <section id="part-b" className="pt-12 scroll-mt-24">
                <SectionHeader
                  eyebrow="Employer-prepared document"
                  heading="Form 16 Part B — What It Contains"
                  icon={Calculator}
                />

                <p className="text-sm leading-8 text-gray-600">
                  Part B of Form 16 is prepared by the employer and details the
                  complete salary computation — the income side of the TDS
                  certificate. It shows how the employer arrived at the taxable
                  salary figure, which deductions and exemptions were considered,
                  and how the final TDS amount was calculated. Part B is the
                  section you will spend the most time reviewing when preparing
                  your ITR.
                </p>

                <div className="mt-6 space-y-3">
                  {PART_B_DETAILS.map(({ item, desc }, idx) => (
                    <div key={item}
                      className="flex items-start gap-4 rounded-2xl border border-gray-100 bg-[#f8fbfd] p-4 hover:shadow-sm transition-all">
                      <div className="w-8 h-8 rounded-lg bg-[#00416a] text-white text-xs font-extrabold flex items-center justify-center shrink-0">
                        {String(idx + 1).padStart(2, "0")}
                      </div>
                      <div>
                        <p className="text-sm font-bold text-gray-800">{item}</p>
                        <p className="mt-1 text-xs leading-relaxed text-gray-600">{desc}</p>
                      </div>
                    </div>
                  ))}
                </div>

                <div className="mt-6 grid md:grid-cols-2 gap-5">
                  <InfoBox title="HRA calculation in Part B" color="amber">
                    <p>
                      The HRA exemption in Part B is based on what the employee
                      declared to the employer. If you pay higher rent or did not
                      submit actual rent receipts to HR, your employer may have
                      under-claimed HRA. You can claim the correct HRA amount
                      while filing your ITR directly, even if Form 16 shows a
                      lower figure — subject to eligibility conditions.
                    </p>
                  </InfoBox>

                  <InfoBox title="Regime selection matters" color="blue">
                    <p>
                      Form 16 Part B reflects the tax regime your employer
                      computed TDS under — new or old. If you declared your
                      regime preference to the employer early in the year, Part B
                      will reflect that. You can, however, switch regimes when
                      filing your ITR, subject to applicable conditions.
                    </p>
                  </InfoBox>
                </div>
              </section>

              {/* How to get */}
              <section id="how-to-get" className="pt-12 scroll-mt-24">
                <SectionHeader
                  eyebrow="Obtaining your document"
                  heading="How to Get Form 16 from Your Employer"
                  icon={Download}
                />

                <p className="text-sm leading-8 text-gray-600">
                  Form 16 is issued by your employer — you cannot download it
                  yourself from the income tax portal. The employer downloads
                  Part A from TRACES after filing the annual TDS return
                  (Form 24Q, Q4) and combines it with internally prepared Part B
                  to create the complete Form 16. Here is the typical process:
                </p>

                <div className="mt-6 space-y-4">
                  {[
                    { step: "01", title: "Employer files annual TDS return", desc: "After the financial year ends, your employer files the fourth-quarter Form 24Q return with TDS details for all employees. This is typically due by May 31." },
                    { step: "02", title: "Part A downloaded from TRACES", desc: "Once the TDS return is processed, the employer logs in to TRACES and downloads Form 16 Part A for each employee. Part A carries a unique TRACES certificate number." },
                    { step: "03", title: "Part B prepared internally", desc: "The employer prepares Part B with the complete salary and deduction details — either in-house payroll software or with assistance from their CA or payroll provider." },
                    { step: "04", title: "Form 16 issued to employee by June 15", desc: "The complete Form 16 (Part A + Part B) is issued to each employee by June 15. Many employers issue it digitally via email or payroll portals." },
                  ].map(({ step, title, desc }) => (
                    <div key={step} className="flex gap-4 items-start rounded-2xl border border-gray-100 bg-[#f8fbfd] p-5">
                      <div className="w-11 h-11 rounded-xl bg-[#00416a] text-white text-sm font-extrabold flex items-center justify-center shrink-0">
                        {step}
                      </div>
                      <div>
                        <h3 className="text-sm font-bold text-gray-800">{title}</h3>
                        <p className="mt-1 text-xs leading-relaxed text-gray-600">{desc}</p>
                      </div>
                    </div>
                  ))}
                </div>

                <InfoBox title="What if your employer has not issued Form 16?" color="rose">
                  <p>
                    If June 15 has passed and your employer has not issued Form 16,
                    first send a written request to the HR or payroll team. If the
                    employer is unresponsive, you can still file your ITR using
                    Form 26AS TDS data, your monthly salary slips, and AIS. You
                    may also report non-issuance to the income tax department.
                    Do not delay ITR filing beyond July 31 while waiting for
                    Form 16.
                  </p>
                </InfoBox>
              </section>

              {/* Using Form 16 for ITR */}
              <section id="itr-filing" className="pt-12 scroll-mt-24">
                <SectionHeader
                  eyebrow="Practical usage"
                  heading="How to Use Form 16 to File Your Income Tax Return"
                  icon={Search}
                />

                <p className="text-sm leading-8 text-gray-600">
                  Form 16 contains almost all the data you need to file ITR-1
                  (Sahaj) or ITR-2 for salaried individuals. Here is how to use
                  each section of Form 16 in your ITR:
                </p>

                <div className="mt-6 overflow-x-auto rounded-2xl border border-gray-100">
                  <table className="w-full min-w-[580px] border-collapse text-left">
                    <thead>
                      <tr className="bg-[#00416a] text-white">
                        <th className="px-5 py-4 text-xs font-bold uppercase tracking-wide">Form 16 data</th>
                        <th className="px-5 py-4 text-xs font-bold uppercase tracking-wide">Where to use in ITR</th>
                      </tr>
                    </thead>
                    <tbody className="text-sm">
                      {[
                        ["Gross salary (Part B)", "Schedule S — Salary income → Gross salary"],
                        ["HRA exemption (Part B)", "Schedule S → Exempt allowances under Section 10"],
                        ["Standard deduction (Part B)", "Schedule S → Standard deduction under Section 16"],
                        ["Professional tax (Part B)", "Schedule S → Entertainment allowance / professional tax"],
                        ["80C deductions (Part B)", "Schedule VI-A → 80C, 80CCC, 80CCD(1)"],
                        ["80D deductions (Part B)", "Schedule VI-A → 80D health insurance"],
                        ["Net taxable salary (Part B)", "Total salary income → Income from salary"],
                        ["TDS amount (Part A)", "Schedule TDS1 → TDS on salary — amount and TAN"],
                      ].map(([data, usage]) => (
                        <tr key={data} className="border-b border-gray-100 last:border-0">
                          <td className="px-5 py-4 font-semibold text-gray-800">{data}</td>
                          <td className="px-5 py-4 text-gray-600">{usage}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>

                <p className="mt-6 text-sm leading-8 text-gray-600">
                  After entering Form 16 data into your ITR, cross-check the
                  TDS amount in Schedule TDS1 against the credit shown in your
                  Form 26AS Part A. Both figures must match before you submit
                  the return. A mismatch at this stage will result in a
                  Section 143(1) demand notice after processing.
                </p>

                <InfoBox title="Multiple employers in the same year" color="amber">
                  <p>
                    If you changed jobs during the financial year, you will
                    receive a separate Form 16 from each employer. Combine the
                    salary figures from both Part Bs, claim deductions only
                    once, and include both TDS entries in Schedule TDS1. If you
                    did not inform your new employer about salary from the
                    previous employer, the new employer may not have deducted
                    sufficient TDS — you may need to pay the shortfall as
                    self-assessment tax before filing.
                  </p>
                </InfoBox>
              </section>

              {/* Reconcile */}
              <section id="reconcile" className="pt-12 scroll-mt-24">
                <SectionHeader
                  eyebrow="Critical step before filing"
                  heading="How to Reconcile Form 16 with Form 26AS and AIS"
                  icon={AlertCircle}
                />

                <p className="text-sm leading-8 text-gray-600">
                  Never file your ITR using Form 16 data alone without verifying
                  it against Form 26AS and AIS. Here is the correct reconciliation
                  sequence:
                </p>

                <ol className="mt-6 space-y-4">
                  {[
                    "Download Form 26AS from the income tax portal or TRACES and verify that the TDS amount and employer TAN in Part A of Form 26AS match exactly with what appears in Form 16 Part A.",
                    "If the TDS amount in Form 26AS is lower than what Form 16 shows, your employer may have deducted TDS but not yet deposited it or may have made an error in the TDS return. Contact HR to resolve this before filing.",
                    "Download AIS from the income tax portal and review all listed income sources — salary, interest, dividend, securities. Confirm that salary income aligns with what Form 16 shows.",
                    "If Form 16 shows deductions your employer computed but you want to change — for example, a higher HRA claim or an additional 80C investment not declared to the employer — you can revise these in the ITR directly.",
                    "Compute tax under both old and new regime if needed. If your employer used the old regime but you prefer the new regime, you can switch while filing the ITR — subject to conditions for business income.",
                    "Pay any self-assessment tax shortfall via Challan 280 on the income tax portal and add the challan details in Schedule IT of the ITR before submitting.",
                  ].map((item, idx) => (
                    <li key={idx} className="flex items-start gap-4">
                      <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#00416a] text-xs font-extrabold text-white">
                        {idx + 1}
                      </span>
                      <p className="pt-1 text-sm leading-7 text-gray-600">{item}</p>
                    </li>
                  ))}
                </ol>
              </section>

              {/* Common mistakes */}
              <section id="mistakes" className="pt-12 scroll-mt-24">
                <SectionHeader
                  eyebrow="Avoid these errors"
                  heading="Common Form 16 Mistakes and How to Avoid Them"
                  icon={AlertCircle}
                />

                <div className="space-y-4">
                  {[
                    {
                      mistake: "Accepting Form 16 without verifying it against Form 26AS",
                      fix: "Always cross-check TDS figures in Form 16 Part A with your Form 26AS before filing. Never assume they match.",
                      color: "border-rose-100 bg-rose-50",
                      textColor: "text-rose-900",
                    },
                    {
                      mistake: "Filing ITR based on Form 16 alone without considering other income",
                      fix: "Form 16 only covers salary income. Bank interest, rental income, capital gains, freelance income and dividend must be separately added to the ITR.",
                      color: "border-amber-100 bg-amber-50",
                      textColor: "text-amber-900",
                    },
                    {
                      mistake: "Missing deductions not declared to the employer",
                      fix: "You can claim additional deductions in your ITR — such as HRA not submitted to HR, 80C investments missed, or 80D premiums not declared — directly when filing, even if they are not in Form 16.",
                      color: "border-blue-100 bg-blue-50",
                      textColor: "text-blue-900",
                    },
                    {
                      mistake: "Not accounting for salary from previous employer",
                      fix: "If you changed jobs, collect Form 16 from both employers. Add both salary incomes and both TDS entries. Compute consolidated tax and pay any shortfall as self-assessment tax.",
                      color: "border-violet-100 bg-violet-50",
                      textColor: "text-violet-900",
                    },
                  ].map(({ mistake, fix, color, textColor }) => (
                    <div key={mistake} className={`rounded-2xl border p-5 ${color}`}>
                      <p className={`text-sm font-extrabold ${textColor} flex items-start gap-2`}>
                        <AlertCircle size={15} className="shrink-0 mt-0.5" /> {mistake}
                      </p>
                      <p className="mt-2 text-xs leading-relaxed text-gray-600">
                        <strong className="text-gray-700">Fix:</strong> {fix}
                      </p>
                    </div>
                  ))}
                </div>
              </section>

              {/* CTA inside article */}
              <div className="mt-12 rounded-3xl bg-gradient-to-br from-[#00416a] to-[#001e36] p-7 md:p-9 text-white">
                <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
                  <div>
                    <p className="text-xs font-bold uppercase tracking-widest text-sky-300">
                      Have your Form 16 ready?
                    </p>
                    <h2 className="mt-2 text-2xl font-extrabold">
                      File your ITR with Taxvio — CA-assisted, from ₹699
                    </h2>
                    <p className="mt-2 max-w-xl text-sm leading-relaxed text-white/65">
                      Share your Form 16 on WhatsApp. Our CA team verifies it
                      against Form 26AS, optimises your deductions and regime,
                      and files your ITR accurately — typically in 1–2 working days.
                    </p>
                  </div>
                  <Link href="/serviceslist/income-tax/itr-salaried"
                    className="inline-flex shrink-0 items-center gap-2 rounded-xl bg-white px-6 py-3.5 text-sm font-bold text-[#00416a] transition hover:bg-gray-50">
                    File ITR Now <ArrowRight size={15} />
                  </Link>
                </div>
              </div>

              {/* FAQ */}
              <section id="faq" className="pt-12 scroll-mt-24">
                <SectionHeader
                  eyebrow="Frequently asked questions"
                  heading="Form 16 FAQs"
                  icon={BookOpen}
                />

                <div className="space-y-3">
                  {FAQS.map(({ question, answer }) => (
                    <details key={question}
                      className="group rounded-2xl border border-gray-100 bg-[#f8fbfd] p-5">
                      <summary className="cursor-pointer list-none pr-6 text-sm font-bold text-gray-800 marker:hidden">
                        <span className="flex items-start gap-3">
                          <span className="text-[#00416a] mt-0.5 shrink-0">Q.</span>
                          {question}
                        </span>
                      </summary>
                      <p className="mt-4 border-t border-gray-200 pt-4 text-sm leading-7 text-gray-600">
                        {answer}
                      </p>
                    </details>
                  ))}
                </div>
              </section>

              {/* Disclaimer */}
              <div className="mt-12 pt-7 border-t border-gray-100">
                <p className="text-xs leading-6 text-gray-500">
                  <strong className="text-gray-700">Disclaimer:</strong> This
                  article is for general educational purposes. Tax rules,
                  Form 16 formats and portal procedures may be updated by the
                  Income Tax Department. Always verify current requirements on
                  incometax.gov.in or consult a qualified CA before filing
                  your return.
                </p>
              </div>
            </article>

            {/* ── Sidebar ── */}
            <aside className="hidden lg:block">
              <div className="sticky top-24 space-y-5">

                {/* TOC */}
                <div className="rounded-2xl border border-[#dcebf3] bg-white p-5 shadow-sm">
                  <p className="text-xs font-bold uppercase tracking-widest text-[#00416a]">
                    On this page
                  </p>
                  <nav className="mt-4 space-y-1.5">
                    {[
                      ["#part-a",     "Form 16 Part A"],
                      ["#part-b",     "Form 16 Part B"],
                      ["#how-to-get", "How to get Form 16"],
                      ["#itr-filing", "Use for ITR filing"],
                      ["#reconcile",  "Reconcile with 26AS & AIS"],
                      ["#mistakes",   "Common mistakes"],
                      ["#faq",        "FAQs"],
                    ].map(([href, label]) => (
                      <a key={href} href={href}
                        className="block rounded-lg px-3 py-2 text-xs font-medium text-gray-600 transition hover:bg-blue-50 hover:text-[#00416a]">
                        {label}
                      </a>
                    ))}
                  </nav>
                </div>

                {/* CTA card */}
                <div className="rounded-2xl bg-[#00416a] p-5 text-white shadow-lg">
                  <div className="w-10 h-10 rounded-xl bg-white/10 flex items-center justify-center">
                    <MessageCircle size={18} className="text-sky-300" />
                  </div>
                  <h3 className="mt-4 text-base font-extrabold">
                    File ITR with Form 16
                  </h3>
                  <p className="mt-2 text-xs leading-relaxed text-white/60">
                    Share your Form 16 on WhatsApp. CA-assisted filing in
                    1–2 working days. Starting ₹699.
                  </p>
                  <Link href="/serviceslist/income-tax/itr-salaried"
                    className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-xs font-bold text-[#00416a] transition hover:bg-gray-50">
                    File ITR Now <ArrowRight size={13} />
                  </Link>
                </div>

                {/* Related services */}
                {[
                  {
                    href: "/guide/itr-blogs/form-26as",
                    label: "Form 26AS Guide",
                    sub: "Understand your tax credit statement",
                    color: "bg-blue-50 border-blue-100",
                    text: "text-blue-700",
                  },
                  {
                    href: "/guide/itr-blogs/income-tax-slabs",
                    label: "Income Tax Slabs",
                    sub: "FY 2025-26 new vs old regime",
                    color: "bg-violet-50 border-violet-100",
                    text: "text-violet-700",
                  },
                ].map(({ href, label, sub, color, text }) => (
                  <Link key={href} href={href}
                    className={`group flex items-center justify-between rounded-2xl border p-5 transition hover:-translate-y-0.5 hover:shadow-md ${color}`}>
                    <div>
                      <p className={`text-xs font-bold uppercase tracking-wide ${text}`}>{label}</p>
                      <p className="mt-1 text-sm font-extrabold text-gray-800">{sub}</p>
                    </div>
                    <ArrowRight size={16} className={`${text} transition group-hover:translate-x-1`} />
                  </Link>
                ))}
              </div>
            </aside>
          </div>
        </section>

        {/* ════════ RELATED GUIDES ════════ */}
        <section className="bg-white border-t border-gray-100 py-16">
          <div className="max-w-6xl mx-auto px-6">
            <div className="mb-8">
              <p className="text-xs font-bold uppercase tracking-widest text-[#0077b6]">
                Explore more
              </p>
              <h2 className="mt-2 text-2xl font-extrabold text-[#00416a]">
                Related Income Tax Guides
              </h2>
            </div>

            <div className="grid gap-4 md:grid-cols-3">
              {[
                {
                  href: "/guide/itr-blogs/form-26as",
                  title: "Form 26AS — Tax Credit Statement",
                  text: "What it contains, how to view and download, and how to resolve TDS mismatches.",
                },
                {
                  href: "/guide/itr-blogs/income-tax-slabs",
                  title: "Income Tax Slabs FY 2025-26",
                  text: "New vs old regime slab rates, Section 87A rebate and calculation examples.",
                },
                {
                  href: "/serviceslist/income-tax/itr-salaried",
                  title: "ITR Filing for Salaried Employees",
                  text: "CA-assisted ITR filing with Form 16, deduction optimisation and e-verification.",
                },
              ].map(({ href, title, text }) => (
                <Link key={title} href={href}
                  className="group rounded-2xl border border-[#dcebf3] bg-[#f8fbfd] p-5 transition hover:-translate-y-1 hover:bg-white hover:shadow-lg">
                  <div className="flex items-center justify-between">
                    <FileText size={18} className="text-[#00416a]" />
                    <ArrowRight size={15} className="text-gray-300 transition group-hover:translate-x-1 group-hover:text-[#00416a]" />
                  </div>
                  <h3 className="mt-4 text-sm font-extrabold text-gray-800 group-hover:text-[#00416a]">
                    {title}
                  </h3>
                  <p className="mt-2 text-xs leading-relaxed text-gray-500">{text}</p>
                </Link>
              ))}
            </div>
          </div>
        </section>

        <Footar />
      </main>
    </>
  );
}